### ISSUE TITLE
CPU Temperature monitoring

### ISSUE THREAD

**Issue by heyiamsven** [MauriceNino/dashdot#36]
**Describe the solution you'd like**
Temperature showing up as a field in the CPU card, or in the graph on hover

**Additional context**
Original:

> after getting dashdot with the newest image to work, I've noticed that CPU temperature isn't monitored, would be quite cool to see this feature in the future.

**Comment by MauriceNino** [comment]
I have edited this issue to follow the projects issue guidelines & split up your question into a separate issue (#37). If you feel like I made a mistake transitioning those issues, feel free to edit them.

**Comment by MauriceNino** [comment]
About the temperature monitoring: what would be the best solution in your opinion? Which features would you need with it?

**Comment by heyiamsven** [comment]
> I have edited this issue to follow the projects issue guidelines & split up your question into a separate issue (#37). If you feel like I made a mistake transitioning those issues, feel free to edit them.

That's totally fine and makes more sense like it is now. Thankyou!

> About the temperature monitoring: what would be the best solution in your opinion? Which features would you need with it?

- I think the best solution would be a graph which has a clickable menu or drop-down to change the view to either 'show last 24 hours' and 'show last X minutes/hour'. 
- In the tab of the graph should be also the following readings available (just in text): highest / middle / lowest temperature readings for the complete uptime (of the device) would be also good.
Example:
> Highest temperature: X *C
> Middle temperature: X *C
> Lowest temperature: X *C

**Comment by MauriceNino** [comment]
> [...] to change the view to either 'show last 24 hours' and 'show last X minutes/hour'.

Not really fond of the idea, tbh - dashdot was never intended to be an all-out monitoring tool. It's more or less the task manager for home servers.

> In the tab of the graph should be also the following readings available (just in text): highest / middle / lowest temperature [...]

That's a tough design choice to be made - I want to keep it simple and not overload the user with information. I don't know where I could fit that in without making it feel cluttered. Maybe I will make it an optional feature though, but for now I don't like the idea of making this the default.

**Comment by heyiamsven** [comment]
I understand that, no problem - maybe instead like this?:
Add the values highest/medium/lowest temperature to the processor-tab (maybe above the graph?) or just add current temperature to it(?) atleast.
And maybe as (optional) feature to enable/disable with a variable to draw temperature lines in the same graph where the cpu-load is shown (in a different color). That way it's pretty easy to compare cpu-load with cpu-temperature.

**Comment by MauriceNino** [comment]
You can now show the average CPU load inside the chart container, by passing the following environment variable:
```
DASHDOT_ENABLE_CPU_TEMPS=true
```

**Comment by heyiamsven** [comment]
Thankyou for adding the feature. After updating the image and enabling the feature I got 0*C shown.
AFAIK my CPU temperature is stored here: /sys/class/thermal/thermal_zone0/temp

The file just stores (i.e. for CPU temp of 31.6*C) in the following format: 31600 (without any text).

Here is a code snipped on how Pihole does retrieve temps:
`# Test existence of temperature file
    if [[ -f "/sys/class/thermal/thermal_zone0/temp" ]]; then
        temp_file="/sys/class/thermal/thermal_zone0/temp"
    elif [[ -f "/sys/class/hwmon/hwmon0/temp1_input" ]]; then
        temp_file="/sys/class/hwmon/hwmon0/temp1_input"
    else
        temp_file=""
    fi`

I'm to unexperienced with coding, so I don't know how to implement that by myself into dashdot, sadly.

Is there - by the way - any way to make a donation for a cup of coffee for you + to support the project?

**Comment by MauriceNino** [comment]
Hm, weird, that is exactly how dashdot retrieves the information. On my setup (Ubuntu 21.x), it works out of the box, without having to mount any volumes. 

But you are running it on a raspberry, if I understand that correctly? Can you look inside the following folder: `/sys/class/hwmon/` and look if there are any sub-folders with the name `hwmon*`? And if there are, can you look inside the folder and see if you find any files with the name `temp*_label`?

Seems like systeminformation uses these files to correctly get the temperatures of every core.

Also, can you maybe see if the command "sensors" returns anything useful on your machine? If you are comfortable with it, please post the result of the command.

About your question on how to support the project - I have added some links to the repo - you can see them when you are on the main page of the project, on the right side, or if you look in the readme :) Thank you!

**Comment by heyiamsven** [comment]
I'm running dashdot on a Odroid N2+ (similar to rPI) with Armbian on it.

In `/sys/class/hwmon/` I have three subfolders called:
> hwmon0
> hwmon1
> hwmon2

In hwmon0 I have a file called temp1_input containing CPU thermal.
In hwmon1 I have a file called temp1_input containing DDR thermal.
In hwmon2 I have gpio_fan related stuff.

Command "sensors" gives me `-bash: sensors: command not found`

**Comment by MauriceNino** [comment]
Can you post the output of `cat /sys/class/hwmon/hwmon0/temp1_input`? So I can compare it with my local file - maybe we can find some discrepancy.

**Comment by heyiamsven** [comment]
> Can you post the output of `cat /sys/class/hwmon/hwmon0/temp1_input`? So I can compare it with my local file - maybe we can find some discrepancy.

Sure. Output is:
32600

**Comment by MauriceNino** [comment]
I have added lm-sensors as a fallback in the image - could you pull the latest dev branch (`mauricenino/dashdot:dev`) and try it out?

**Comment by heyiamsven** [comment]
Unfortunately, it still shows 0.0 *C after pulling the newest docker image.

**Comment by MauriceNino** [comment]
Sorry, I have forgotten that you are using ARM builds - I have pushed for ARM now, can you please recheck?

**Comment by heyiamsven** [comment]
Installed the dev ARM build, thankyou.

Step 1 & 2 don't give me logs, after executing step 3 I got the following output:
> gpio_fan-isa-0000
> Adapter: ISA adapter
> fan1:        1600 RPM  (min =    0 RPM, max = 1600 RPM)
> 
> cpu_thermal-virtual-0
> Adapter: Virtual device
> temp1:        +33.1°C  (crit = +110.0°C)
> 
> ddr_thermal-virtual-0
> Adapter: Virtual device
> temp1:        +34.7°C  (crit = +110.0°C)

But frontend of dashdot still shows 0.0 *C

**Comment by heyiamsven** [comment]
> Output shows more info for me, so that might be the problem:
> 
> ```
> ucsi_source_psy_USBC000:002-isa-0000
> Adapter: ISA adapter
> in0:           5.00 V  (min =  +5.00 V, max =  +5.00 V)
> curr1:         0.00 A  (max =  +0.00 A)
> 
> iwlwifi_1-virtual-0
> Adapter: Virtual device
> temp1:        +44.0°C  
> 
> dell_smm-isa-0000
> Adapter: ISA adapter
> fan1:        3194 RPM
> fan2:        3501 RPM
> 
> nvme-pci-6d00
> Adapter: PCI adapter
> Composite:    +37.9°C  (low  =  -0.1°C, high = +74.8°C)
>                        (crit = +79.8°C)
> 
> ucsi_source_psy_USBC000:003-isa-0000
> Adapter: ISA adapter
> in0:           5.00 V  (min =  +5.00 V, max =  +5.00 V)
> curr1:         0.00 A  (max =  +0.00 A)
> 
> ucsi_source_psy_USBC000:001-isa-0000
> Adapter: ISA adapter
> in0:           5.00 V  (min =  +5.00 V, max =  +5.00 V)
> curr1:         0.00 A  (max =  +0.00 A)
> 
> coretemp-isa-0000
> Adapter: ISA adapter
> Package id 0:  +56.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 0:        +54.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 1:        +55.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 2:        +54.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 3:        +56.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 4:        +55.0°C  (high = +100.0°C, crit = +100.0°C)
> Core 5:        +55.0°C  (high = +100.0°C, crit = +100.0°C)
> 
> pch_cometlake-virtual-0
> Adapter: Virtual device
> temp1:        +48.0°C  
> 
> BAT0-acpi-0
> Adapter: ACPI interface
> in0:          13.16 V  
> curr1:         1.05 A
> ```
> 
> Have you tried installing `lm-sensors` on your host and running `sudo sensors-detect`?

Yes, here is the output:
> # sensors-detect version 3.6.0
> # Kernel: 5.10.103-meson64 aarch64
> # Cannot show processor info on aarch64 architecture.
> 
> This program will help you determine which kernel modules you need
> to load to use lm_sensors most effectively. It is generally safe
> and recommended to accept the default answers to all questions,
> unless you know what you're doing.
> 
> Some south bridges, CPUs or memory controllers contain embedded sensors.
> Do you want to scan for them? This is totally safe. (YES/no): y
> modprobe: FATAL: Module cpuid not found in directory /lib/modules/5.10.103-meson64
> Failed to load module cpuid.
> Silicon Integrated Systems SIS5595...                       No
> VIA VT82C686 Integrated Sensors...                          No
> VIA VT8231 Integrated Sensors...                            No
> AMD K8 thermal sensors...                                   No
> AMD Family 10h thermal sensors...                           No
> AMD Family 11h thermal sensors...                           No
> AMD Family 12h and 14h thermal sensors...                   No
> AMD Family 15h thermal sensors...                           No
> AMD Family 16h thermal sensors...                           No
> AMD Family 17h thermal sensors...                           No
> AMD Family 15h power sensors...                             No
> AMD Family 16h power sensors...                             No
> Hygon Family 18h thermal sensors...                         No
> Intel digital thermal sensor...                             No
> Intel AMB FB-DIMM thermal sensor...                         No
> Intel 5500/5520/X58 thermal sensor...                       No
> VIA C7 thermal sensor...                                    No
> VIA Nano thermal sensor...                                  No
> 
> Lastly, we can probe the I2C/SMBus adapters for connected hardware
> monitoring devices. This is the most risky part, and while it works
> reasonably well on most systems, it has been reported to cause trouble
> on some systems.
> Do you want to probe the I2C/SMBus adapters now? (YES/no): y
> Sorry, no supported PCI bus adapters found.
> 
> Next adapter: Meson I2C adapter (i2c-0)
> Do you want to scan it? (YES/no/selectively): y
> Client found at address 0x51
> Handled by driver `rtc_pcf8563' (already loaded), chip type `pcf8563'
>     (note: this is probably NOT a sensor chip!)
> 
> Next adapter: Meson I2C adapter (i2c-1)
> Do you want to scan it? (YES/no/selectively): y
> 
> Next adapter: DesignWare HDMI (i2c-2)
> Do you want to scan it? (YES/no/selectively): y
> 
> Sorry, no sensors were detected.
> Either your system has no sensors, or they are not supported, or
> they are connected to an I2C or SMBus adapter that is not
> supported. If you find out what chips are on your board, check
> https://hwmon.wiki.kernel.org/device_support_status for driver status.

**Comment by MauriceNino** [comment]
Okay, I think I will have to create a feature request on `systeminformation` then. One last thing - can you try executing `sensors` on your host, just to make sure, that there is no core information given?

**Comment by heyiamsven** [comment]
Hey, I just wanted to report back that temperature reading is now working for me. Thankyou very much! :)

**Comment by MauriceNino** [comment]
Thanks for the update! Glad it is working now :)
